# Generated by Django 4.2.7 on 2023-11-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='idade',
            field=models.CharField(default='', max_length=2),
        ),
    ]
